### ISSUE TITLE
Keycaps configuration

### ISSUE THREAD

**Issue by hasufell** [dpapavas/lagrange-keyboard#1]
I'm having a hard time figuring out whether I can buy pre-printed keycaps at least for the regular main char-keys and which types those are. Do I have to print all of them myself? Do you have a list of all the used keycaps and their position?

From what I see, those are standard SA R3 1u?

----
Edit:

So I made an overview.

Keycap | Section | Custom | Pieces (per unit) | Pieces (total)
---------- | ---------- | ---------- | ---------------------- | -----------------
**SA** R3 1u **concave** | main | No | 22 | 44
**SA** R3 1.5u **concave** | main (outer column) | No | 4 | 8
**SA** R3 1.5u saddle | wrist | Yes | 1 | 2
_DSA_ 1u **concave** | thumb | No | 3 | 6
_DSA_ 1u _convex_ | thumb | ?? | 1 | 2
_DSA_ 1.25u _convex_ | thumb | ?? | 1 | 2
_DSA_ 1.5u _convex_ | thumb | ?? | 2 | 4
_DSA_ 1u _convex_ fanged | thumb | Yes | 1 | 2

For the DSA convex keys, I'm not sure if there are some available in shops. Is this table correct?

Useful keycap form overview: https://i.redd.it/6mx9e4xdfvk11.jpg

**Comment by dpapavas** [comment]
As I haven't been very clear on this matter in the documentation, I have now [added a section](https://github.com/dpapavas/lagrange-keyboard/blob/master/BUILD.md#keycaps) on it to the build guide.  As you can see there, your table is generally correct.  You can use SA or DSA keycaps according to taste, but note that the height will affect the effective geometry, so that taller keys for instance, might be more comfortable for smaller hands, but feel cramped for longer fingers.  This concerns the default design of course; if you customize it, you should use whatever keycaps you developed and tested your design with.  Please have a look at the new section in the build guide and let me know if further clarification is required.

I have not been able to find convex keycaps in any profile for sizes smaller that 3u or so, therefore, even if they may be available from exotic sources, they're custom as far as I'm concerned.

**Comment by hasufell** [comment]
Thanks! I'm also working on a complete shopping list for my build and found a few small things missing here and there, e.g. which diodes to use, probably 1N4148, which tools are needed and so on. I think that's useful for beginners who haven't done soldering or 3d printing yet, to have a proper overview. I'll open a new issue/PR once I'm confident my list is exhaustive.
