### ISSUE TITLE
Default finger length?

### ISSUE THREAD

**Issue by hasufell** [dpapavas/lagrange-keyboard#2]
I'd find it useful to know the finger lengths that correspond to the default settings, so I have a better idea with what values to play. This could reduce the number of test prints considerably.

**Comment by dpapavas** [comment]
I have posted some measurements in [this reply](https://www.reddit.com/r/ErgoMechKeyboards/comments/l2vxlx/my_recently_finished_design_the_lagrange_keyboard/glld2cr/).  I quote the relevant portion below, but you might want to read the rest of the comments in the reply as well:

> My thumb measures about 53mm from carpometacarpal joint to metacarpophalangeal joint and maybe another 75mm or so from there to the tip. My middle finger measures about 53mm from metacarpophalangeal joint to proximal interphalangeal joint and another 60mm or so, from there to the tip. I would assume that the other fingers would compare similarly.

In the build guide, I also describe the basic idea of how to get ballpark estimates of the radii and column offsets, based on measurements of your own hand (which should explain why I don't give measurements of just total finger length above).

I should stress what I say in the guide, that you should err on the "larger" side, as a slightly "loose" geometry, is preferable to a slightly "cramped" one.  I designed the default settings with SA keycaps in mind, but as it turns out, I was probably a bit too aggressive and with SA keycaps, the keyboard would feel fine most of the time, but sometimes (I suppose when my hands started to tire, or perhaps when the placement on the desk wasn't just right) it would feel "weird", and my hands couldn't type entirely comfortably no matter what.  I tried switching to DSA keycaps and it's been fine ever since.

(This might also suggest another approach, if you're not too fussy about aesthetics: design aggressively with SA keycaps in mind and if you find that you've ended up with an overtight design, switch to DSA or KAM profile.)
