### ISSUE TITLE
Some slicers have problems with right.stl/left.stl

### ISSUE THREAD

**Issue by hasufell** [dpapavas/lagrange-keyboard#4]
The Prusa slicer seems to have problems with the `right.stl` and `left.stl` files, creating borked slice model (2nd picture). This seems to happen even if I regenerate the scad file and re-export to stl.

![Screenshot_2021-03-23_15-13-18](https://user-images.githubusercontent.com/1241845/112177267-0c098480-8bf9-11eb-9512-46200984608e.png)
![Screenshot_2021-03-23_15-13-28](https://user-images.githubusercontent.com/1241845/112177289-1035a200-8bf9-11eb-8605-05db843f3b88.png)

I had to run it through an online service such as https://www.formware.co/onlinestlrepair before it worked. On the other hand, it worked without any fixing in Cura.

I'm not sure what could be the reason for this or if it makes sense to investigate, since there's an easy workaround. Ppl told me it's probably OpenSCAD exporting the stl file. Maybe a note in the build guide would be handy?

**Comment by dpapavas** [comment]
This is not critical as you note, but it is troubling nevertheless, as it may be that there's something wrong with the generated model that Cura just works around.  I've only used Cura up until now, but I'll try to install the Prusa slicer and investigate this when I  find some time.

Just to be clear: this happens with *both* left and right sides, correct?  Also, I notice that the slice shows a :warning: next to `left.stl`.  Does it offer any explanation for what went wrong, in the form of log/error messages?

**Comment by hasufell** [comment]
> Just to be clear: this happens with both left and right sides, correct?

Yep.

>  Does it offer any explanation for what went wrong, in the form of log/error messages?

I can't find any. But the online tool that fixed it showed this:
![Screenshot_2021-03-23_17-06-19](https://user-images.githubusercontent.com/1241845/112314647-88f43700-8ca9-11eb-9cd9-c98cecaba27d.png)

**Comment by dpapavas** [comment]
Hmmmm...  Well the part about "duplicate faces" doesn't seem bad, but the other two issues do (well, for the sake of correctness at least; I don't think they have any impact on the final build, at least for Cura, or after fixing).  Thanks for the report.  I'll look into it.

**Comment by dpapavas** [comment]
The problem was caused by parts of the model which weren't "2-manifold".  It's hard to be sure about how exactly this came about, but in general, the problem seems to have been caused by my striving to be "exact" when making the geometry of the model.  As such certain parts, such as the mating areas of the individual key plates and the interconnecting geometry of the top plate, or the top parts of the side walls, were calculated to line up exactly, but, due to floating point errors and whatnot, didn't really always do so, leading to strange, albeit not readily visible results.

These are mostly fixed now.  PrusaSlicer says the mesh is manifold, but there seem to remain a couple of non-manifold edges, which it doesn't detect.  At any rate, it seems to slice properly now, but, since you're probably more experienced with PrusaSlicer, you may want to have a look and reopen the issue if necessary.

**Comment by hasufell** [comment]
That works for me as well.
