### ISSUE TITLE
Screws

### ISSUE THREAD

**Issue by hasufell** [dpapavas/lagrange-keyboard#5]
From the source code it says:

1. the threads for the main cover are [6.5mm diameter](https://github.com/dpapavas/lagrange-keyboard/blob/4300aa79c275c61619fc59f06c003e3002768eba/src/lagrange_keyboard/core.clj#L203)
2. the threads for the pcb are [5mm diameter](https://github.com/dpapavas/lagrange-keyboard/blob/4300aa79c275c61619fc59f06c003e3002768eba/src/lagrange_keyboard/core.clj#L233)

I'm suspecting the correct screws are:
1. M6 H12/H13 8mm length
2. M5 H12 6mm length

However, the M5 I have lying around here don't fit through the PCB, which in the source code says correctly is [3mm diameter](https://github.com/dpapavas/lagrange-keyboard/blob/4300aa79c275c61619fc59f06c003e3002768eba/src/lagrange_keyboard/core.clj#L421).

Did you use some sort of dowel? Shouldn't the thread dimensions be calculated from the PCB hole size?

Additionally some guidance as to which types of screws (apart from dimensions) work well would be appreciated. For example there's quite extensive discussion about plastic and screws here: https://www.stanleyengineeredfastening.com/-/media/web/sef/resources/docs/other/threaded_fasteners_for_plastics.ashx

**Comment by dpapavas** [comment]
The default setup is designed for use with self-tapping threaded inserts.  I already cover the subject in detail in the build guide, mentioning both what threaded inserts you'll need and how to install them, but I also added a photo of the parts, so that you can have an idea what they look like.  See [here](https://github.com/dpapavas/lagrange-keyboard/blob/master/BUILD.md#installing-the-threaded-inserts) for more information.

As I also mention in the build guide, the correct screws are M4 (6-8mm length should be fine) countersunk screws for the case (something like DIN 7991 / ISO 10642) and whatever style of M3-6mm screws you like for the PCB.  (I went with button-head screws, in the style of DIN 9427 / ISO 7380).  Make sure not to overtighten the screws (a bit more than fingertight should be more than enough).

If you don't want to use this type of threaded insert for some reason, it should be straightforward to change the code for use with other inserts, such as the ones you install with a soldering iron.  For the bottom cover, you could technically just print threads for direct use with a fastener, but at 0.2mm layer height, the vertical resolution isn't entirely adequate, even for M5 threads.  Apart from that, printed threads would cross-thread easily and be prone to wear out.  Printing M3 threads for the PCB is out of the question, as far as I can tell.

In any case, I suggest printing test builds of a single boss, to make sure the insert installs properly (and also get some practice), before tackling application on the production part.

**Comment by hasufell** [comment]
Thanks, it seems I missed that between all the printing :exploding_head: 

----

Unrelatedly, my first Lagrange test print:

![photo_2021-03-25_18-39-37](https://user-images.githubusercontent.com/1241845/112518323-90930900-8d99-11eb-8343-1805d24b547e.jpg)

I just used the keycaps from my ergodox for testing. I'll probably adjust the middle row (I find the `8` hard to reach) and will increase radius for the pinky finger (I reach for `0` and `P` with my ring finger instead of pinky... is that uncommon?). I'll also experiment with row curvature. I find the thumb section the hardest to reason about. First I thought that I want to get rid of the lower thumb section (the lower 4 keys), because I felt it interferes with my lower hand. But then I realized it's because I'm having a tilted wrist, which I shouldn't.

**Comment by dpapavas** [comment]
>Thanks, it seems I missed that between all the printing

That's understandable, but I need to stress that you *really* shouldn't rush this.  Most steps of the build can be pretty challenging and in many cases a mistake can't be easily repaired, so you lose the accumulated time (and money) of the work until that point.  That's why I tried to find approaches that would simplify hard to execute steps (in the sense of reducing the chance of failure) as much as possible and described them in detail in the build guide.  (Don't interpret this as a complaint, but as perhaps overly cautious advice.)

>Unrelatedly, my first Lagrange test print:

That looks very good!  The silver color makes the PETG sheen look almost bearable, too. :)

>I'll probably adjust the middle row (I find the `8` hard to reach) and will increase radius for the pinky finger (I reach for 0 and P with my ring finger instead of pinky... is that uncommon?)

At the risk of becoming tiresome, allow me to quote the build guide:

>When testing out prints, keep the following points in mind. Even if the geometry is optimal, your fingers will still not be used to it, so don't expect to be able to type straight away. Ideally, your fingers should be able to reach all keys of the main section by mere rotation, without running into nearby keycaps as they do so. Given that our hands can adapt to infinite radius (i.e. a flat keyboard), it would probably be wise to err on the side of larger radius.

Let me add a few more remarks to make this more specific, in view of your comments above.

A conventional keyboard is largely unadapted to the human hand.  As a result the hand has to adapt to it, and many different methods (i.e. habits) will work well enough.  Ergonomic keyboards on the other hand are adapted to the hand, and in order to be able to do that, they need to make assumptions about how they will be used and base the design on those.  As such, your best bet is most likely to switch to a "conventional" typing technique.  (Although I believed to touch-type by the book, I found out that this wasn't the case when I got an Ergodox.  What worked for my previous conventional staggered keyboard, simply didn't work with its columnar layout).

Apart from that, tailoring the geometry to your needs presents the following challenge: In general, if you haven't typed in a very similar keyboard before, you *cannot* determine what will work best in the end from experience (with more conventional keyboards).  Stated in other words: you should assume that you'll need to get used to this keyboard, that your hands will need to learn and adapt to it, so that it will feel alien at first.   Trying to change the keyboard, so that it is to your liking straight away, means (at best) you'll change it to something close to the keyboards you have already.  (At worst, you'll change it to something unusable.)

Consider the issue of the `8` key you mention:  How easy it is to reach that, depends not only on the curvature, but also on the attitude (i.e. the positioning) of your hand relative to the keyboard.  If you rotate you hand a little around the "row" axis (i.e. if you pitch it), you'll find the `8` key easier to reach but the bottom key of the column will now be further away.  Similarly, due to the tenting angle, keeping your hand still, but rotating the keyboard on the desk (around the vertical axis), will have a similar effect.

Since you can't determine what will work from quick experimentation, you'll have to design the geometry around some *principle* and hope that it'll work out in the end.  I know that this is a bit of gamble and therefore less than desirable and believe me, I've been there, but I can't see a way around it.  To quote the guide again:

>Mount switches and keycaps and make sure that the keys are accessible with the minimum of strain, that is, without needing to extend the fingers more than necessary, and without needing to contract them to clear the keycaps. The latter would be a sign of insufficiently large column and/or row radii. A small row radius would also cause the sides of the middle and ring fingers to drag against the sides of the keycaps of the neighboring columns.

What this means in the present case is, that if you can position your hand so that both the `8` and the opposite key on the same column can be reached by the middle finger without needing to either "reach", or curl it up, then the geometry is likely fine.  (Of course, you'll have to be able to do that to an adequate degree for *all* the columns at the same time.)

>But then I realized it's because I'm having a tilted wrist, which I shouldn't.

The same applies here.  If you can position your hand in such a way (regardless of how you currently type, or of your expectations), so that it is relaxed and can reach the upper row of the thumb section by mere rotation, without strain (at least for the first 3 keys), then assume it's fine.  The lower "cross-like" section requires some motion of the palm to reach, but it's meant for less frequently used keys.  I can, having my hand entirely relaxed, rest my fingers on the home row (`j`, `k`, `l`, `;`) and have my thumb rest (entirely relaxed) on the second (from the inside) key of the first thumb row.  Then, by mere rotation, I can reach the neighboring two keys. I'd expect this (more or less) to be the case for you as well.

**Comment by hasufell** [comment]
> That looks very good! The silver color makes the PETG sheen look almost bearable, too. :)

It's a quick PLA build, so I'm expecting to have at least 3 more prints or so before I settle for a final build. I don't think I'm rushing it ;)

In the worst case... I have the utilities for 3 full builds.

>  What worked for my previous conventional staggered keyboard, simply didn't work with its columnar layout).

I'm currently using the kinesis advantage 2 with touch-typing, which has pretty similar curvature. The main differences to lagrange geometry are:

1. kinsesis is less tented
2. has almost no column offset
3. and stronger row curvature
4. (isn't actually a split keyboard, but that's less relevant wrt geometry)

So switching to a dactyl style keyboard isn't a big jump. The biggest change will be the tenting.

>  If you rotate you hand a little around the "row" axis (i.e. if you pitch it), you'll find the 8 key easier to reach but the bottom key of the column will now be further away. Similarly, due to the tenting angle, keeping your hand still, but rotating the keyboard on the desk (around the vertical axis), will have a similar effect.

Yeah. I'm also not sure how I will position my hand. I think this is a much bigger question compared to the kinesis, where I float my hands like handling a marionette. So there you basically have only two  main positions: wrist down or wrist up. There's not much angle you can change.

That said... whatever I do, `8` is hard to reach and for `P` I generally dislike extending my pinky upwards. So... I'm pretty sure I have one main principle figured out for me: **avoid lateral wrist movement as much as possible**. This movement definitely occurs when I reach for the middle row on the thumb cluster, because of the 33 degrees angle (my next build will have all angles at 6 degrees, so it'll be more like a staircase thumb cluster). Likewise, stretching my ring finger outwards is rather comfortable to me and requires little to no wrist movement.
The other principle probably is: **avoid upwards stretching of fingers**. Most keyboard layouts assume the top row is more comfortable than the bottom row... I have a very strong opinion against it and in fact have tap-hold keys for ctrl/alt/win on my bottom row. All of this considered... I don't mind moving the hand as a whole or bending the wrist inwards, but stretching fingers upwards and lateral wrist movement are those two main things I wanna avoid.

**Comment by hasufell** [comment]
## Wrt geometry

### Middle row adjustment

I played all night with the parameters and I can't find a way to do what I want with the middle row: pull the tip of the column towards me. It's not the height (that pulls the entire column towards me, not just the tip) and it's not the the column radius either.

Basically: I like how the first 2-3 rows are aligned in x,y and z... just the upper two rows need adjustment.

### lateral curvature

I'm also experimenting with an increased curvature of the outer 2 columns (both left and right) inwards. However, adjusting `row-radius` causes immense increase in tilt and changes the thumb cluster, board height etc (I guess it might be possible to compensate post-adjusting thumb cluster and `global-z-offset`, but it seems hard).

The main idea here is that lateral finger travel of both index finger and pinky finger (pretty much the only ones that normally travel laterally) is reduced slightly due to increased lateral curvature of the outermost columns. Lateral movement is really the RSI devil, whether it's wrist or fingers.

### Tenting

Another thing I'd just like to experiment with and haven't found a way yet. I doubt I will actually make use of this idea if it's possible, but the idea is that one leg is longer than the other, rotating the board towards or away from me.

**Comment by dpapavas** [comment]
>I played all night with the parameters and I can't find a way to do what I want with the middle row: pull the tip of the column towards me.

I'm not sure I understand you.  You say you want to do something with the middle row, but then mention the tip of the column, which is not in the middle row.

I'll try to answer generally.  As I mentioned above, the keys are not laid out arbitrarily, but around a principle.  Essentially, the keys are laid out on the inside surface of a torus (a donut) of given radii.  You can describe a location on that surface by two angles along the red and blue directions shown [here](https://upload.wikimedia.org/wikipedia/commons/d/db/Toroidal_coord.png), say a "longitude" and "latitude" of sorts, sweeping along rows and columns respectively.  The `column/row-phase` parameters define the common initial angle of whole columns/rows, so if you change that, the whole column or row will *rotate* up/down or left/right respectively.  The `row/column-spacing` parameters define the angle increment from one key on the column/row to the next, so the (curvilinear) distance between consecutive rows/columns.  The `column-offset/height` shift whole columns linearly horizontally or vertically up/down respectively.

These parameters are chosen, because they're deemed to match the geometry of the hand: your fingers can rotate to sweep a (more or less) torroidal surface, but each finger is not the same.  The length of the proximal phalanx differs, necessitating the horizontal shift afforded by `column-offset`.  Their overall lengths also differ, necessitating the vertical shift determined by `column-height` and the different radii set by `column-radius`.  Finally in their relaxed state, the tips don't fall on the same line, which can be accommodated by the curvilinear shifts possible via `column-phase`.

If I understand correctly, that you want to change the height, meaning the vertical offsets of specific keys, then that is not currently possible.  It might be easy to hack the code to do so.

>I'm also experimenting with an increased curvature of the outer 2 columns (both left and right) inwards.

Again, not sure what you mean by the "curvature" of the outer two columns.  You *can* change the curvature of separate columns, via `column-radius`, but I suspect you want to rotate the outer columns, so that they face more towards the center.  You can't currently do that and, again, it might be easy to hack the code, or it might be tricky.

>The main idea here is that lateral finger travel of both index finger and pinky finger (pretty much the only ones that normally travel laterally) is reduced slightly due to increased lateral curvature of the outermost columns. 

I see the point, but rotating the columns enough to make a difference, will also make the keycap top angled relative to the direction of the finger, making it harder and more uncomfortable to press.  It will also make wiring the `5`/`6` columns quite a bit harder than they already are.  On a practical level, if you actually rotate the whole column, you'll need to increase the distance of, say the `R`/`T` and `F`/`G` keys, otherwise the `V`/`B` and `4`/`5` keys will interfere.  Rotating each key along its local Y axis will accomplish something like what (AFAICT) you want, but now the keytops of the column won't be "continuous", i.e. they won't like on a cylindrical surface any more.  I'm not sure how that would work out either.

> [...] the idea is that one leg of the stand is longer than the other, rotating the board towards or away from me.

Again, not possible with the current tenting-stand (and it would be tricky both to procedurally generate and to configure geometry that bolts onto the bottom cover and affords 3DOF attitude control), but you can achieve any amount of adjustability you want by a simple alternative:  ditch the stand and get three M4 hex standoffs of suitable lengths, plus matching M4 grub screws and attach to 3 bottom cover bolt holes (with washers to cover the countersunk areas).  By adjusting the lengths of each leg, you can get any attitude you want (at an inevitable cost in overall keycap distance from the desktop).

**Comment by hasufell** [comment]
> If I understand correctly, that you want to change the height, meaning the vertical offsets of specific keys, then that is not currently possible.

I want to control the Z position of the following two keys while keeping the radius for the column:

![lagrange_keyboard](https://user-images.githubusercontent.com/1241845/112820499-f1665e00-9085-11eb-9590-36f025588c31.png)

The reason is simple: the lower one of this key is misaligned imo. It becomes clear when using the following patch:

```diff
--- a/src/lagrange_keyboard/core.clj
+++ b/src/lagrange_keyboard/core.clj
@@ -78,7 +78,7 @@

 (def column-height #(case %
                       (0 1) 0
-                      2 -5
+                      2 0
                       3 0
                       7))
```

resulting in odd positioning of those keys that don't match the row height anymore.

![Screenshot_2021-03-29_12-01-05](https://user-images.githubusercontent.com/1241845/112822279-0ba13b80-9088-11eb-86cb-cbbd1e83e0c7.png)

That's why the current code uses `-5`, to align the lower key on the Z-axis, but that results in very deep positioning of the upper key.

----

I don't believe this aligns with hand geometry at all. When bending your fingers inwards, your tips start to more and more align in a straight line:

![bent-inwards](https://user-images.githubusercontent.com/1241845/112822074-be24ce80-9087-11eb-902e-b2208a3cc324.jpg)

When you straighten your fingers, the difference becomes larger.

![straigth](https://user-images.githubusercontent.com/1241845/112822096-c5e47300-9087-11eb-8564-2b9e4fe77856.jpg)

This difference is accounted for by the **column offset** already. Pushing the upper keys down the Z axis moves the key even further away, so you will compensate with hand/wrist movement. I've tried over the course of several days and I wasn't able to create natural movement to those upper two keys. Reducing the column height is a no-option as you can see in the picture above, because it will cause a huge bump on the lower key.

>  It might be easy to hack the code to do so.

I tried and I wasn't able to find a solution with my limited knowledge of SCAD and geometry. Any pointers would be appreciated. I believe this is a crucial parameter for adjustment.

**Comment by hasufell** [comment]
Omg, I'm an idiot... it is indeed `column-phase` and its relationship with `column-offset`. To achieve higher Z coordinates on the top keys of a column, you have to remove some of the column-offset, adjust column-phase to move the column back "up" and then adjust column-height to fix the bottom key.

E.g.:

----

## Patch

```diff
--- a/src/lagrange_keyboard/core.clj
+++ b/src/lagrange_keyboard/core.clj
@@ -48,39 +48,39 @@

 (def row-spacing #(case %
                     (0 1) 7/2
-                    2 13/4
+                    2 7/2
                     3 13/4
                     9/2))

 (def column-spacing #(case %
                        0 2
-                       1 0
+                       1 1
                        2 9/2
-                       3 5
+                       3 3
                        3))

 ;; Column and row rotations in units of keys.

 (def row-phase (constantly -8))
 (def column-phase (fn [i] (+ -57/25 (cond
-                                      (= i 2) -1/4
+                                      (= i 2) -1/3
                                       (= i 3) -1/8
-                                      (> i 3) -1/4
+                                      (> i 3) 0.1
                                       :else 0))))

 ;; Column offsets, in mm, in the Y and Z axes.

 (def column-offset #(case %
                       (0 1) 0
-                      2 8
+                      2 2
                       3 0
-                      -14))
+                      -5))

 (def column-height #(case %
-                      (0 1) 0
-                      2 -5
+                      (0 1) 1
+                      2 -2
                       3 0
-                      7))
+                      1))

 ;; The key scale of the outer columns.
```

----

## Orig

![Screenshot_2021-03-29_15-30-53](https://user-images.githubusercontent.com/1241845/112844784-69dc1780-90a4-11eb-8971-986f51b16790.png)

## New

![Screenshot_2021-03-29_15-30-45](https://user-images.githubusercontent.com/1241845/112844813-6fd1f880-90a4-11eb-8414-67f155cdb2f1.png)

----

Does that make sense?

**Comment by dpapavas** [comment]
> [...] it is indeed `column-phase` and its relationship with `column-offset`. To achieve higher Z coordinates on the top keys of a column, you have to remove some of the column-offset, adjust column-phase to move the column back "up" and then adjust column-height to fix the bottom key.
> [...]
> Does that make sense?

Yes, I think so, assuming you take Z to point away from you. (I take X and Y to be on the plane of the desktop,  pointing, loosely speaking, "along the rows" and "along the columns".  Z is then upwards, at right angles to the desktop.  This is also the convention in the program.)

Regarding the hand ergonomics effect you point out, I believe it is addressed in the current geometry:  The difference in finger length is taken into account by having both different radii and different heights per column.  Together with the column offsets, this results in the upper rows having much more pronounced height differences than the lower rows, where the keys are essentially on the same height.  Still, if you can change the configuration to work better for you, by all means go ahead and do so.

**Comment by hasufell** [comment]
Just reporting my progress so far. I managed to achieve the lateral curvature increase quite well by the following patch:

```diff
--- a/src/lagrange_keyboard/core.clj
+++ b/src/lagrange_keyboard/core.clj
@@ -36,7 +36,7 @@

 ;; The radius, in mm, for each column, or for each row.

-(def row-radius 235)
+(def row-radius 160)
 (def column-radius #(case %
                       (0 1) 65
                       2 69
@@ -61,7 +61,7 @@

 ;; Column and row rotations in units of keys.

-(def row-phase (constantly -8))
+(def row-phase (constantly -6))
 (def column-phase (fn [i] (+ -57/25 (cond
                                       (= i 2) -1/4
                                       (= i 3) -1/8
@@ -141,7 +141,7 @@

 ;; Height offset for the whole keyboard.

-(def global-z-offset 0)
+(def global-z-offset 8)

 ;; Case-related parameters.
```

Result (amongst other changes):

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1241845/113202893-a0b05a00-926b-11eb-9b0f-a6ced88a93cc.gif)

**Comment by dpapavas** [comment]
Looks good!  I did also try to increase row curvature (i.e. decrease the radius), as it would certainly make reaching the outer columns easier.  From what I remember, the problem I noticed in my test prints, was that the fingers tended to feel "cramped" by the neighboring columns, especially where these neighboring columns had large height differences (for instance, when reaching for the `W` or `2` keys, the finger would brush, or rather drag, against the `1` column).  This might have been due to the tall SA keycaps though and shorter caps, like DSA, might be able to sustain smaller row radii.  It might also be workable with SA caps, given time to adapt; I didn't try it in a working build.

You might want to consider altering the row phase to make the outer (right in the picture above) column horizontal.  It will in essence increase tenting (which you can further adjust via the stand) with similar cost in material and printing time.  The benefit would be a larger height at the other end (allowing you more adjustment at the thumb section, should you need it) and, I think, a more favorable thumb-to-main-section angle.

Also, as mentioned in the build guide, make sure to run interference tests before printing after such changes, to make sure you won't run into trouble mounting the switches and caps.

**Comment by hasufell** [comment]
> Looks good! I did also try to increase row curvature (i.e. decrease the radius), as it would certainly make reaching the outer columns easier. 

Yes, I had the same... I ended up doing another test build without the row curvature. The pinky columns are very uncomfortable and would at least need much larger column spacing to separate it from the ring finger.

> You might want to consider altering the row phase to make the outer (right in the picture above) column horizontal. It will in essence increase tenting (which you can further adjust via the stand) with similar cost in material and printing time. The benefit would be a larger height at the other end (allowing you more adjustment at the thumb section, should you need it) and, I think, a more favorable thumb-to-main-section angle.

Hmm, I might give that another shot. It sounds like that would essentially look like the advantage kinesis 2 row curvature: almost flat at ring to pinky rows and strong curvature from middle to outer index finger rows. But I'm not sure how much more I'm willing to print, I already have 4 test prints :o

I'm also not sure that this micromanagement will get me anywhere. I think it's possible to just get the rough geometry right and then fine-tune with custom keycaps. Everything is possible there. I'm utilizing https://github.com/rsheldiii/KeyV2 and already have cumstom height SA2 keycaps in mind for the upper rows. To allow my ring finger to travel to the upper pinky keys, I will maybe utilize g20 (very low height) keycaps.

**Comment by dpapavas** [comment]
>Hmm, I might give that another shot. It sounds like that would essentially look like the advantage kinesis 2 row curvature: almost flat at ring to pinky columns and strong curvature from middle to outer index finger columns.

The *curvature*, i.e. the angle difference from on column to the next,  is constant.  It just looks flatter at one end and more curved at the other because your brain interprets one end as flat, because it is parallel to the desk, a surface it knows to be "flat", while at the other end, the constant curvature has accumulated enough angle with respect to a known horizontal surface, so that it appears visibly curved.  But all this is merely "illusion", so to speak; the final effect of a phase change is equivalent to that of rotation of the whole part, that's why, disregarding tenting, which will ultimately also depend on the stand configuration, the only difference with respect to ergonomics, should be the relative position and attitude of the main and thumb sections.

> But I'm not sure how much more I'm willing to print, I already have 4 test prints
> I'm also not sure that this micromanagement will get me anywhere. I think it's possible to just get the rough geometry right and then fine-tune with custom keycaps.

Yes, one has to draw the line at some point and call it "good enough".  Adjustment at this level certainly exhibits diminishing returns.

**Comment by hasufell** [comment]
> The curvature, i.e. the angle difference from on column to the next, is constant. It just looks flatter at one end and more curved at the other because your brain interprets one end as flat, because it is parallel to the desk, a surface it knows to be "flat", while at the other end, the constant curvature has accumulated enough angle with respect to a known horizontal surface, so that it appears visibly curved. But all this is merely "illusion", so to speak; the final effect of a phase change is equivalent to that of rotation of the whole part, that's why, disregarding tenting, which will ultimately also depend on the stand configuration, the only difference with respect to ergonomics, should be the relative position and attitude of the main and thumb sections.

Ah, I see. Have you ever had a closer look at the advantage kineses 2 geometry? I'm pretty sure it isn't a torus wrt row curvature. There seems to be more  curvature on the index finger sides:

![IMG_20210326_203824](https://user-images.githubusercontent.com/1241845/113563230-a01b1900-9607-11eb-84b7-b5ac9755a00a.jpg)
![IMG_20210326_203815](https://user-images.githubusercontent.com/1241845/113563243-a7422700-9607-11eb-9c96-370fe4ef1551.jpg)
![IMG_20210326_203829](https://user-images.githubusercontent.com/1241845/113563332-d0fb4e00-9607-11eb-8cb6-c16f3801f210.jpg)

**Comment by dpapavas** [comment]
> Ah, I see. Have you ever had a closer look at the advantage kineses 2 geometry? I'm pretty sure it isn't a torus wrt row curvature. There seems to be more curvature on the index finger sides

Yes, I have.  Note first that, even on the Lagrange, the key surface isn't exactly a torus.  If we wanted to be more accurate, I guess we could say it's "piecewise torus-like" or something like this.  That's because the basic geometry is that of a torus, but since the curvature and Y/Z offset can be set independently for each column, the first and last pair of columns and each of the remaining two fall on different tori.  I'm mentioning this to point out that, as you can see both in the configuration and by inspection of the geometry, the curvature does change for each of the above column groups, in a way, more or less similar, to the Advantage.

That said, I'm having a hard time making sense of some aspects of the geometry of the Advantage.  My guess is that the geometry, is constrained by manufacturing considerations.  The PCBs used for instance are not of the flex type, but rather simply thin conventional PCBs.  This means they can only bend so far before there's danger of breaking, which in turn sets a limit on the achievable curvature.  Perhaps this is why angled keycaps (OEM I believe) have been mostly used, as they allow augmenting the curvature of the chassis (or reducing it, as in some cases they seem to be mounted the other way round).

Perhaps the design is guided by purely ergonomic concerns and presents benefits that escape me though.  Comparing geometries for optimality is not very easy.  To be objective, one really has to build or buy both options and spend as much time as needed to find the best performance achievable with each one, since otherwise one would be biased by their accustomed typing technique.  Coupled by the fact that the possibilities are really endless, this necessitates, as I have mentioned, some sort of guiding principle, optimism in assuming that sound theory will lead to good practical results and sufficient self-control to draw the line somewhere and declare the design "optimal".

**Comment by hasufell** [comment]
I've made some progress with the controller, but when I plug it in and run `avrdude -c usbtiny -p m32u4` I get

```
avrdude: Error: Could not find USBtiny device (0x1781/0xc9f)
```

I'm suspecting the controller may be dead due to incorrect soldering. Any ideas on how to debug that? I'm not too experienced with soldering. I checked only for shorts, especially on the microcontroller and couldn't find any.

----

![IMG_20210419_092422](https://user-images.githubusercontent.com/1241845/115197848-bdfd7900-a0f1-11eb-8d62-c31de01fac87.jpg)

![IMG_20210419_092443](https://user-images.githubusercontent.com/1241845/115197906-cb1a6800-a0f1-11eb-9756-64aba2336c85.jpg)

**Comment by hasufell** [comment]
I also checked all capacitors and resistors... they seem to be ok. But I have no idea how to check whether the CPU is damaged.

**Comment by dpapavas** [comment]
I don't see anything obviously wrong with the microcontroller and associated components, but on the second photo of the backside, your USB port seems to be missing a pin and the large supporting ground pins aren't soldered.  Why is that?

Apart from that, you shouldn't be using `avrdude`.  The message you get is natural, in that you're not using the `USBtiny` ISP programmer, so it can't find it.  (If you are using the `USBtiny`, then the error is still unrelated to the functional state of the board, as it can't find the programmer in the first place, so the condition of the board does not matter at this point.)

The Mega32 comes with the DFU bootloader, so you should be using `dfu-programmer`.  The easiest way to see if the microcontroller is working normally, would be to check whether the PC detects the bootloader.  When you first plug in the board, before programming it for the first time (or when you press the reset button, once you've programmed it) the controller should load the bootloader.  You don't mention your OS, but assuming you're running Linux, doing something like:

```sudo dmesg -w```

and then plugging in the board (and pressing the button for good measure), you should see something like the following:

```[ 8162.620387] usb 3-1.1: new full-speed USB device number 6 using xhci_hcd
[ 8162.723230] usb 3-1.1: New USB device found, idVendor=03eb, idProduct=2ff4, bcdDevice= 0.00
[ 8162.723238] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 8162.723243] usb 3-1.1: Product: ATm32U4DFU
[ 8162.723247] usb 3-1.1: Manufacturer: ATMEL
[ 8162.723251] usb 3-1.1: SerialNumber: 1.0.0
```

Seeing the above would mean that the microcontroller itself is working fine (although some of its I/O connections might still have problems, but you can troubleshoot that later, if necessary).  To further test the device you might try something like the following, to verify that you can communicate with the bootloader:

```$ dfu-programmer atmega32u4 get bootloader-version
Bootloader Version: 0x00 (0)
$ dfu-programmer atmega32u4 get ID1
Device boot ID 1: 0x00 (0)```

**Comment by hasufell** [comment]
I re-soldered a fresh USB connector onto the board, tested the pins. Still nothing.

**Comment by hasufell** [comment]
Oh... I figured it out! It was the crystal. It was short on all edges (I wasn't sure whether it has to be or not... first I thought I had too little solder, so I added more to make it short). Apparently the surface of it is leading so if the solder touches it, you quickly get shorts.

**Comment by dpapavas** [comment]
The crystal case is probably connected to ground, so it should be shorted to 2 of the 4 pins.  You probably shorted one or both of the the crystal terminals, essentially bypassing the clock.  Glad you sorted it out. :+1:
